image: node:12-alpine

cache:
  key: project
  paths:
    - .yarn
    - node_modules

stages:
  - install
  - test
  - pages

install:
  stage: install
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn

test:
  stage: test
  script:
    - yarn audit
    - yarn lint --check
    - yarn test

pages:
  stage: pages
  script:
    - yarn build --mode='production'
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
